version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: node_auth
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql

  ecommerce:
    image: ecommerce-app
    container_name: ecommerce_apps
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: pass123
      DB_NAME: node_auth
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
